# Generated by Django 4.0.3 on 2023-10-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valores',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
